import { DoFCharKey } from "../models/enums";

export const getSupportKey = (unit1: string, unit2: string) => {
    let u1, u2;
    if (unit1 < unit2) {
        u1 = unit1;
        u2 = unit2;
    } else {
        u1 = unit2;
        u2 = unit1;
    }
    return `${u1}__${u2}`;
}

export const SupportData: { [key: string]: { base: number, speed: number, paired?: boolean } } = {
    [`${DoFCharKey.Kolbane}__${DoFCharKey.Rena}`]: { base: 5, speed: 3 },
    [`${DoFCharKey.Garath}__${DoFCharKey.Rena}`]: { base: 15, speed: 5 },
    [`${DoFCharKey.Adalheid}__${DoFCharKey.Rena}`]: { base: 0, speed: 32 },
    [`${DoFCharKey.Amaryl}__${DoFCharKey.Rena}`]: { base: 0, speed: 32 },
    [`${DoFCharKey.Franseza}__${DoFCharKey.Seren}`]: { base: 241, speed: 0, paired: true },
    [`${DoFCharKey.Artemisia}__${DoFCharKey.Franseza}`]: { base: 45, speed: 6 },
    [`${DoFCharKey.Eudira}__${DoFCharKey.Franseza}`]: { base: 35, speed: 6 },
    [`${DoFCharKey.Garath}__${DoFCharKey.Kolbane}`]: { base: 15, speed: 5 },
    [`${DoFCharKey.Amelia}__${DoFCharKey.Eilene}`]: { base: 30, speed: 4 },
    [`${DoFCharKey.Amelia}__${DoFCharKey.Artemisia}`]: { base: 15, speed: 8 },
    [`${DoFCharKey.Amelia}__${DoFCharKey.Rozelle}`]: { base: 15, speed: 5 },
    [`${DoFCharKey.Jauger}__${DoFCharKey.Kolbane}`]: { base: 30, speed: 6 },
    [`${DoFCharKey.Kolbane}__${DoFCharKey.Thyra}`]: { base: 50, speed: 5, paired: true },
    [`${DoFCharKey.Asher}__${DoFCharKey.Gabriel}`]: { base: 15, speed: 4 },
    [`${DoFCharKey.Asher}__${DoFCharKey.Dismas}`]: { base: 65, speed: 6 },
    [`${DoFCharKey.Asher}__${DoFCharKey.Chester}`]: { base: 5, speed: 4 },
    [`${DoFCharKey.Eilene}__${DoFCharKey.Ioan}`]: { base: 15, speed: 4 },
    [`${DoFCharKey.Eilene}__${DoFCharKey.Sheila}`]: { base: 80, speed: 7 },
    [`${DoFCharKey.Crowe}__${DoFCharKey.Driscoll}`]: { base: 20, speed: 4 },
    [`${DoFCharKey.Driscoll}__${DoFCharKey.Odette}`]: { base: 15, speed: 6 },
    [`${DoFCharKey.Conleth}__${DoFCharKey.Driscoll}`]: { base: 15, speed: 3 },
    [`${DoFCharKey.Driscoll}__${DoFCharKey.Lizaveta}`]: { base: 30, speed: 4 },
    [`${DoFCharKey.Chester}__${DoFCharKey.Crowe}`]: { base: 30, speed: 3 },
    [`${DoFCharKey.Chester}__${DoFCharKey.Conleth}`]: { base: 25, speed: 4, paired: true },
    [`${DoFCharKey.Chester}__${DoFCharKey.Cyrille}`]: { base: 45, speed: 5 },
    [`${DoFCharKey.Arcus}__${DoFCharKey.Lizaveta}`]: { base: 0, speed: 7 },
    [`${DoFCharKey.Ioan}__${DoFCharKey.Lizaveta}`]: { base: 5, speed: 4 },
    [`${DoFCharKey.Bellona}__${DoFCharKey.Lizaveta}`]: { base: 15, speed: 6, paired: true },
    [`${DoFCharKey.Crowe}__${DoFCharKey.Dismas}`]: { base: 45, speed: 4 },
    [`${DoFCharKey.Blixa}__${DoFCharKey.Corbeau}`]: { base: 15, speed: 5 },
    [`${DoFCharKey.Blixa}__${DoFCharKey.Rozelle}`]: { base: 20, speed: 3, paired: true },
    [`${DoFCharKey.Blixa}__${DoFCharKey.Marie}`]: { base: 30, speed: 4 },
    [`${DoFCharKey.Ioan}__${DoFCharKey.Seren}`]: { base: 10, speed: 5 },
    [`${DoFCharKey.Arcus}__${DoFCharKey.Jolyon}`]: { base: 45, speed: 5 },
    [`${DoFCharKey.Arcus}__${DoFCharKey.seMori}`]: { base: 30, speed: 5 },
    [`${DoFCharKey.Arcus}__${DoFCharKey.Stolypin}`]: { base: 30, speed: 7 },
    [`${DoFCharKey.Alexis}__${DoFCharKey.Stolypin}`]: { base: 15, speed: 6, paired: true },
    [`${DoFCharKey.Stolypin}__${DoFCharKey.Wren}`]: { base: 15, speed: 4 },
    [`${DoFCharKey.Rotariu}__${DoFCharKey.Stolypin}`]: { base: 200, speed: 15 },
    [`${DoFCharKey.Florent}__${DoFCharKey.Marin}`]: { base: 30, speed: 7 },
    [`${DoFCharKey.Florent}__${DoFCharKey.Jolyon}`]: { base: 30, speed: 8 },
    [`${DoFCharKey.Cathale}__${DoFCharKey.Florent}`]: { base: 10, speed: 5 },
    [`${DoFCharKey.Cyrille}__${DoFCharKey.Florent}`]: { base: 5, speed: 6 },
    [`${DoFCharKey.Jolyon}__${DoFCharKey.Marin}`]: { base: 30, speed: 8 },
    [`${DoFCharKey.Cothiva}__${DoFCharKey.Marin}`]: { base: 15, speed: 5 },
    [`${DoFCharKey.Amaryl}__${DoFCharKey.Cothiva}`]: { base: 65, speed: 9 },
    [`${DoFCharKey.Cathale}__${DoFCharKey.Cothiva}`]: { base: 10, speed: 5, paired: true },
    [`${DoFCharKey.Gabriel}__${DoFCharKey.Wren}`]: { base: 15, speed: 3, paired: true },
    [`${DoFCharKey.Eudira}__${DoFCharKey.Gabriel}`]: { base: 15, speed: 7 },
    [`${DoFCharKey.Cyrille}__${DoFCharKey.Gabriel}`]: { base: 15, speed: 4 },
    [`${DoFCharKey.Annelise}__${DoFCharKey.Rozelle}`]: { base: 30, speed: 4 },
    [`${DoFCharKey.Annelise}__${DoFCharKey.Volund}`]: { base: 75, speed: 5, paired: true },
    [`${DoFCharKey.Annelise}__${DoFCharKey.Thyra}`]: { base: 35, speed: 10 },
    [`${DoFCharKey.Jolyon}__${DoFCharKey.Meliza}`]: { base: 15, speed: 9, paired: true },
    [`${DoFCharKey.Kai}__${DoFCharKey.Meliza}`]: { base: 60, speed: 20 },
    [`${DoFCharKey.Meliza}__${DoFCharKey.Severin}`]: { base: 30, speed: 8 },
    [`${DoFCharKey.seMori}__${DoFCharKey.Sileth}`]: { base: 30, speed: 5 },
    [`${DoFCharKey.seMori}__${DoFCharKey.viShen}`]: { base: 15, speed: 4 },
    [`${DoFCharKey.Adalheid}__${DoFCharKey.Conleth}`]: { base: 0, speed: 30 },
    [`${DoFCharKey.Conleth}__${DoFCharKey.Lyndra}`]: { base: 15, speed: 5 },
    [`${DoFCharKey.Kahn}__${DoFCharKey.Wren}`]: { base: 45, speed: 5 },
    [`${DoFCharKey.Bellona}__${DoFCharKey.Kahn}`]: { base: 10, speed: 3 },
    [`${DoFCharKey.Kahn}__${DoFCharKey.Leda}`]: { base: 10, speed: 3 },
    [`${DoFCharKey.Bellona}__${DoFCharKey.Claudiya}`]: { base: 60, speed: 20 },
    [`${DoFCharKey.Corbeau}__${DoFCharKey.Seren}`]: { base: 15, speed: 6 },
    [`${DoFCharKey.Baldur}__${DoFCharKey.Leda}`]: { base: 10, speed: 5, paired: true },
    [`${DoFCharKey.Baldur}__${DoFCharKey.Nari}`]: { base: 30, speed: 3 },
    [`${DoFCharKey.Baldur}__${DoFCharKey.Nikita}`]: { base: 0, speed: 6 },
    [`${DoFCharKey.Alexis}__${DoFCharKey.Leda}`]: { base: 15, speed: 6 },
    [`${DoFCharKey.byorDal}__${DoFCharKey.Nari}`]: { base: 15, speed: 3 },
    [`${DoFCharKey.Nari}__${DoFCharKey.Sileth}`]: { base: 15, speed: 3, paired: true },
    [`${DoFCharKey.Nikita}__${DoFCharKey.viShen}`]: { base: 15, speed: 6 },
    [`${DoFCharKey.Thyra}__${DoFCharKey.viShen}`]: { base: 15, speed: 6 },
    [`${DoFCharKey.Hereward}__${DoFCharKey.Jauger}`]: { base: 50, speed: 9 },
    [`${DoFCharKey.Jauger}__${DoFCharKey.Odette}`]: { base: 50, speed: 9 },
    [`${DoFCharKey.Hereward}__${DoFCharKey.Odette}`]: { base: 40, speed: 5 },
    [`${DoFCharKey.byorDal}__${DoFCharKey.Hereward}`]: { base: 45, speed: 6, paired: true },
    [`${DoFCharKey.Artemisia}__${DoFCharKey.Hereward}`]: { base: 60, speed: 12 },
    [`${DoFCharKey.Saskia}__${DoFCharKey.Sheila}`]: { base: 30, speed: 12 },
    [`${DoFCharKey.Lyndra}__${DoFCharKey.Saskia}`]: { base: 15, speed: 12 },
    [`${DoFCharKey.Artemisia}__${DoFCharKey.Sheila}`]: { base: 40, speed: 10 },
    [`${DoFCharKey.Thyra}__${DoFCharKey.Volund}`]: { base: 75, speed: 6 },
    [`${DoFCharKey.Dismas}__${DoFCharKey.Tricia}`]: { base: 60, speed: 6 },
    [`${DoFCharKey.Amaryl}__${DoFCharKey.Marie}`]: { base: 30, speed: 15 },
    [`${DoFCharKey.Marie}__${DoFCharKey.Severin}`]: { base: 15, speed: 6 },
    [`${DoFCharKey.Brill}__${DoFCharKey.Nikita}`]: { base: 30, speed: 6, paired: true },
    [`${DoFCharKey.Brill}__${DoFCharKey.Sileth}`]: { base: 15, speed: 5 },
    [`${DoFCharKey.Brill}__${DoFCharKey.Tricia}`]: { base: 15, speed: 7 },
    [`${DoFCharKey.byorDal}__${DoFCharKey.Volund}`]: { base: 15, speed: 7 },
    [`${DoFCharKey.Morwen}__${DoFCharKey.Severin}`]: { base: 30, speed: 8, paired: true },
    [`${DoFCharKey.Adalheid}__${DoFCharKey.Lyndra}`]: { base: 75, speed: 30, paired: true },
    [`${DoFCharKey.Alexis}__${DoFCharKey.Amaryl}`]: { base: 30, speed: 8 },
    [`${DoFCharKey.Alexis}__${DoFCharKey.Cyrille}`]: { base: 45, speed: 5 },
    [`${DoFCharKey.Cathale}__${DoFCharKey.Sileth}`]: { base: 15, speed: 6 },
    [`${DoFCharKey.Lyndra}__${DoFCharKey.Morwen}`]: { base: 161, speed: 4 },
    [`${DoFCharKey.Eudira}__${DoFCharKey.Tricia}`]: { base: 15, speed: 5 }
};
